return {
	{
		"xiyaowong/transparent.nvim",
		config = function()
			require("transparent").setup({
				groups = {
					"Normal",
					"NormalNC",
					"Comment",
					"Constant",
					"Special",
					"Identifier",
					"Statement",
					"PreProc",
					"Type",
					"Underlined",
					"Todo",
					"String",
					"Function",
					"Conditional",
					"Repeat",
					"Operator",
					"Structure",
					"LineNr",
					"NonText",
					"SignColumn",
					"CursorLine",
					"CursorLineNr",
					"StatusLine",
					"StatusLineNC",
					"EndOfBuffer",
				},
				extra_groups = {
					"NormalFloat",
					"NvimTreeNormal",
					"BufferLineTabClose",
					"BufferlineBufferSelected",
					"BufferLineFill",
					"BufferLineBackground",
					"BufferLineSeparator",
					"BufferLineIndicatorSelected",
					"IndentBlanklineChar",
					"LspFloatWinNormal",
					"FloatBorder",
					"TelescopeNormal",
					"TelescopeBorder",
					"TelescopePromptBorder",
					"SagaBorder",
					"SagaNormal",
					"NeoTree.*",
					"StatusLine",
					"StatusLineNC",
					"BqfPreviewFloat",
					"TreesitterContext",
					"Pmenu",
					"DapUI.*",
					"Telescope.*",
					"TabLineFill",
					"TreesitterContextLineNumber",
					"QuickFixLine",
					"Notify.*",
					"WhichKeyFloat",
				},
				highlights = {
					init = {
						Normal = { bg = "NONE", ctermbg = "NONE" },
						NormalNC = { bg = "NONE", ctermbg = "NONE" },
						NormalFloat = { bg = "NONE", ctermbg = "NONE" },
						EndOfBuffer = { bg = "NONE", ctermbg = "NONE" },
						SignColumn = { bg = "NONE", ctermbg = "NONE" },
						CursorLine = { bg = "NONE", ctermbg = "NONE" },
						CursorLineNr = { bg = "NONE", ctermbg = "NONE" },
						WinSeparator = { bg = "NONE", ctermbg = "NONE" },
						StatusLine = { bg = "NONE", ctermbg = "NONE" },
						StatusLineNC = { bg = "NONE", ctermbg = "NONE" },
						Pmenu = { bg = "NONE", ctermbg = "NONE" },
						PmenuSel = { bg = "NONE", ctermbg = "NONE" },
						FloatBorder = { bg = "NONE", ctermbg = "NONE" },
						TelescopeBorder = { bg = "NONE", ctermbg = "NONE" },
						TelescopePromptBorder = { bg = "NONE", ctermbg = "NONE" },
						TreesitterContext = { bg = "NONE", ctermbg = "NONE" },
					},
				},
			})

			require("transparent").clear_prefix("BufferLine")
			require("transparent").clear_prefix("Telescope")
		end,
	},
}
