return {
	require("plugins.core.init"),
	require("plugins.lsp.init"),
	require("plugins.ui.init"),
	require("plugins.auto-close"),
	require("plugins.auto-format"),
	require("plugins.auto-pairs"),
	require("plugins.codesnap"),
	require("plugins.comment"),
	require("plugins.lazyclip"),
	require("plugins.markdown"),
	require("plugins.surround"),
	require("plugins.themery"),
	require("plugins.tmux-navigation"),
	require("plugins.todo-comments"),
	require("plugins.trouble"),
	require("plugins.wakatime"),
}
